version: 2.1

orbs:
  release-management: salesforce/npm-release-management@4

workflows:
  version: 2
  release:
    jobs:
      - release-management/validate-pr:
          filters:
            branches:
              ignore: main
      - release-management/release-package:
          github-release: true
          filters:
            branches:
              only: main
  dependabot-automerge:
    triggers:
      - schedule:
          cron: '0 2,5,8,11 * * *'
          filters:
            branches:
              only:
                - main
    jobs:
      - release-management/dependabot-automerge

